apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processor
  template:
    metadata:
      labels:
        app: video-processor
    spec:
#      volumes:
#        - name: storage
#          persistentVolumeClaim:
#            claimName: videoprocessor-pvc
      containers:
      - name: video-processorx
        image: antoniodsaf/video-processor:latest
        ports:
        - containerPort: 8085
        envFrom:
        - secretRef:
            name: videoprocessor-secret
